export const GET_ERRORS="GET_ERRORS";
export const GET_WALLETS="GET_WALLETS";
export const GET_WALLET="GET_WALLET";
export const DELETE_WALLET="DELETE_WALLET";
export const UPDATE_WALLET="UPDATE_WALLET";

export const GET_TRANSACTIONS="GET_TRANSACTIONS";
export const GET_TRANSACTION="GET_TRANSACTION";
export const ADD_TRANSACTION="ADD_TRANSACTION";
export const DELETE_TRANSACTION="DELETE_TRANSACTION";

export const GET_USER = "GET_USER"
export const GET_USERS = "GET_USERS"